### ISSUE TITLE
HTTPError

### ISSUE THREAD

**Issue by UnclassedPenguin** [manvari/imgur-scraper#1]
Hello, Everytime I try to run this, i get:

Traceback (most recent call last):
  File "/usr/local/bin/imgur-scrape", line 14, in <module>
    imgur_resource = scraper.prepare_url(args.client_id, args.url)
  File "/usr/local/lib/python2.7/dist-packages/imgurscraper/scraper.py", line 22, in prepare_url
    request = client.request(imgur_resource)
  File "/usr/local/lib/python2.7/dist-packages/imgurscraper/imgur.py", line 24, in request
    request.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

Is this something wrong on my side? 
Thanks

**Comment by manvari** [comment]
Have you checked the resources you're trying to scrape still exist on imgur? imgur-scrape works just fine for me when I try to download an album from the front page:

```
$ imgur-scrape -v redacted https://imgur.com/gallery/RdGLn ~/Images 
Album ID: RdGLn
Number of images: 5
Downloaded 1/5
Downloaded 2/5
Downloaded 3/5
Downloaded 4/5
Downloaded 5/5
Finished downloading the album.
```

**EDIT**: I suppose you're trying to scrape a single picture or a subreddit? imgur-scraper only supports (gallery) _albums_, so imgur picture & subreddit URLs aren't properly formatted by the prepare_url function; hence the 404. I'll get my lazy butt working on that, soon enough.

**Comment by bekamahaile** [comment]
please help me any one to understand this problem
Traceback (most recent call last):
  File "./loadbalancer.py", line 332, in <module>
    loadbalance()
  File "./loadbalancer.py", line 265, in loadbalance
    getLinkCost()
  File "./loadbalancer.py", line 147, in getLinkCost
    getResponse(stats,"linkTX")
  File "./loadbalancer.py", line 26, in getResponse
    response.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found
